"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
files: [
  {
    "source": "src/locales/en-US/*.json",
    "translation": "src/locales/%locale%/%original_file_name%",
  }
]
