name: ci

on:
  push:
    branches:
      - 'dev'
      - 'live'
  pull_request:
    branches:
      - 'dev'
      - 'live'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        npm ci
        npm test

  docker:
    needs: build
    if: ${{ github.ref == 'refs/head/live' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rabbithousecorp/chinokafuu:${{ steps.extract_branch.outputs.branch }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
