name: Test

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    
jobs:
  jesus:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Send Jesus
        run: |
          echo "jesus eh mais"
          echo "jesus eh mais"
          echo "jesus eh mais"
          mkdir quem-ler-e-gay
          la
